name: CI Develop
on:

  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler
      - name: Install Gems
        run: bundle install
      - name: Run Rubocop
        run: |
          bundle exec rubocop

  database:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        ports: [ '5432:5432' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler
      - name: Install Gems
        run: bundle install

      - name: Setup database
        env:
          PG_DATABASE: postgres
          PG_HOST: 127.0.0.1
          PG_USER: postgres
          PG_PASSWORD: postgres
          RAILS_ENV: test
          WITH_COVERAGE: true
          DISABLE_SPRING: 1
        run: |
          bundle exec rails db:prepare
          bundle exec rake test

  rspec:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        ports: [ '5432:5432' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler
      - name: Install Gems
        run: bundle install
      - name: Build and test with rspec
        env:
          PG_DATABASE: postgres
          PG_HOST: 127.0.0.1
          PG_USER: postgres
          PG_PASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundle exec rspec spec